[workspace]
members = [
    "crates/use-chemistry",
    "crates/use-element",
    "crates/use-chemical-formula",
    "crates/use-stoichiometry",
    "crates/use-bond",
    "crates/use-oxidation-state",
    "crates/use-ion",
    "crates/use-compound",
    "crates/use-molecule",
    "crates/use-isotope",
    "crates/use-periodic-table",
    "crates/use-atomic-number",
    "crates/use-atomic-mass",
    "crates/use-electron-shell",
]
resolver = "2"

[workspace.package]
authors = ["RustUse Contributors"]
edition = "2024"
homepage = "https://rustuse.org"
license = "MIT OR Apache-2.0"
publish = false
readme = "README.md"
repository = "https://github.com/RustUse/use-chemistry"
rust-version = "1.95.0"
version = "0.1.0"

[workspace.dependencies]
use-atomic-mass = { version = "0.1.0", path = "crates/use-atomic-mass" }
use-atomic-number = { version = "0.1.0", path = "crates/use-atomic-number" }
use-bond = { version = "0.1.0", path = "crates/use-bond" }
use-chemical-formula = { version = "0.1.0", path = "crates/use-chemical-formula" }
use-stoichiometry = { version = "0.1.0", path = "crates/use-stoichiometry" }
use-oxidation-state = { version = "0.1.0", path = "crates/use-oxidation-state" }
use-ion = { version = "0.1.0", path = "crates/use-ion" }
use-compound = { version = "0.1.0", path = "crates/use-compound" }
use-molecule = { version = "0.1.0", path = "crates/use-molecule" }
use-electron-shell = { version = "0.1.0", path = "crates/use-electron-shell" }
use-element = { version = "0.1.0", path = "crates/use-element" }
use-isotope = { version = "0.1.0", path = "crates/use-isotope" }
use-periodic-table = { version = "0.1.0", path = "crates/use-periodic-table" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.metadata.rustuse.release]
publish = false
versioning = "lockstep-0.x"
first-publish-candidates = [
    "use-element",
    "use-isotope",
    "use-chemical-formula",
    "use-stoichiometry",
    "use-bond",
    "use-oxidation-state",
    "use-ion",
    "use-compound",
    "use-molecule",
    "use-periodic-table",
    "use-atomic-number",
    "use-atomic-mass",
    "use-electron-shell",
    "use-chemistry",
]
[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
expect_used = "warn"
multiple_crate_versions = "allow"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
todo = "deny"
unimplemented = "deny"
unwrap_used = "warn"
