[package]
name = "use-stoichiometry"
description = "Stoichiometry primitives for RustUse"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage = "https://github.com/RustUse/use-chemistry"
documentation = "https://docs.rs/use-stoichiometry"
keywords = ["chemistry", "stoichiometry", "reaction", "formula", "yield"]
categories = ["science", "data-structures"]

[dependencies]
use-chemical-formula.workspace = true

[package.metadata.docs.rs]
all-features = true
