[package]
name = "use-chemistry"
publish = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
rust-version.workspace = true
description = "Composable chemistry primitives for RustUse."
documentation = "https://docs.rs/use-chemistry"
keywords = ["chemistry", "bond", "compound", "molecule", "formula"]
categories = ["science", "data-structures"]

[dependencies]
use-atomic-mass.workspace = true
use-atomic-number.workspace = true
use-bond.workspace = true
use-chemical-formula.workspace = true
use-compound.workspace = true
use-molecule.workspace = true
use-electron-shell.workspace = true
use-element.workspace = true
use-isotope.workspace = true
use-periodic-table.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
